// ======================================                                               ======================================
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    Problem 4: Finding Bad data                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ======================================                                               ======================================

function findingBadData(numberArray) {
  let badData = [];

  //   badData is an empty array. it has no element right now...

  if (Array.isArray(numberArray) !== true) {

    return "Please..!! Input a valid ~~ Array ~~ of numbers...";

    // this condition is for checking the input value is an array or not... if the input value is not an array it will give a error message.

  } else {

    for (let i = 0; i < numberArray.length; i++) {

      // this loop is for generating the values of array serially.

      const element = numberArray[i];

      //   element store the values which was generated by the loop...

      if (element < 0) {

        badData.push(element);

        //  the values which were smaller than "0" was pushed or added into a new array called "badData"...
      }

    }

  }


  return badData.length;

  //   as all the Bad Data was pushed into an array called "badData"... So the badData array's length which refers to the number of elements in badData... array is equal to the number of Bad Data that Input array has...

}


// this ~~~~ findingBadData() ~~~~ function takes array as an input.. then sort it by adding negative numbers in an empty array..

// calculates the array length and return the length as a result... cause it represents how many Bad Data or negative number the actual array has.... 



// const example24 = findingBadData([1, 2, 5]);
// console.log(example24);

// const example25 = findingBadData([2, -5, -7, -13]);
// console.log(example25);

// const example26 = findingBadData([-4, -9, -5, -33, -55]);
// console.log(example26);

// const example32 = findingBadData([]);
// console.log(example32);

// const example27 = findingBadData({ a: 3, b: 6, c: 85 });
// console.log(example27);

// let example28 = findingBadData("23465");
// console.log(example28);

// let example29 = findingBadData(true);
// console.log(example29);

// let example30 = findingBadData(1056411564512);
// console.log(example30);

// const example31 = findingBadData([-4, -9, -5, -33, -55, 20, -51, -41, -7]);
// console.log(example31);
