
// ======================================                                               ======================================
// ======================================                                               ======================================
// ~~~~~~~~~~~~~~~~~~~~~~~~~~~~                    Problem 4: Finding Bad data                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
// ======================================                                               ======================================
// ======================================                                               ======================================

function findingBadData(numberArray) {
    let badData = [];
  
    //   badData is an empty array. it has no element right now...
  
    if (Array.isArray(numberArray) !== true) {
      return "Please..!! Input a valid ~~ Array ~~ of numbers...";
  
      // this condition is for checking the input value is an array or not... if the input value is not an array it will give a error message.
    } else {
      for (let i = 0; i < numberArray.length; i++) {
        // this loop is for generating the values of array serially.
  
        const element = numberArray[i];
  
        //   element store the values which was generated by the loop...
  
        if (element < 0) {
          badData.push(element);
  
          //  the values which were smaller than "0" was pushed or added into a new array called "badData"...
        }
      }
    }
  
    return badData.length;
    //   as all the Bad Data was pushed into an array called "badData"... So the badData array's length which refers to the number of elements in badData... array is equal to the number of Bad Data that Input array has...
  }
  
  const numbers = [1, 2, 5, -10];
  const d = findingBadData(numbers);
  console.log(d);
  